# The full repository name
repo: gitea/changelog

# Service type (gitea or github)
service: gitea

# Base URL for Gitea instance if using gitea service type (optional)
# Default: https://gitea.com
base-url: https://gitea.com

# Changelog groups and which labeled PRs to add to each group
groups:
  -
    name: FEATURES
    labels:
      - feature
  -
    name: BUGFIXES
    labels:
      - bug
  -
    name: ENHANCEMENTS
    labels:
      - enhancement
  -
    name: BUILD
    labels:
      - build
  -
    name: MISC
    default: true

# regex indicating which labels to skip for the changelog
skip-labels: skip-changelog