---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:

- name: build
  pull: always
  image: golang:1.13
  environment:
    GOPROXY: https://goproxy.cn
  commands:
  - go test -race

- name: discord
  pull: always
  image: appleboy/drone-discord:1
  environment:
    DISCORD_WEBHOOK_ID:
      from_secret: discord_webhook_id
    DISCORD_WEBHOOK_TOKEN:
      from_secret: discord_webhook_token
  when:
    event:
    - push
    - tag
    status:
    - changed
    - failure

trigger:
  branch:
  - master